name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/danielwolbach/galactic-ci-image:latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: |
          cargo check
      - name: Lint
        run: |
          cargo fmt --check
          cargo clippy
      - name: Build
        run: |
          cargo build
